### ISSUE TITLE
What exactly are left and right windows are represent ?

### ISSUE THREAD

**Issue by Azperin** [aianlinb/LibGGPK3#12]
When I have used `ExtractBundledGGPK3.exe` with no second argument it extracts right window, but why not videos folder from left window ?

![screenshot](https://i.imgur.com/uXX9wDb.png)

**Comment by aianlinb** [comment]
Left one are bundles and videos in ggpk.
Right one are files compressed in bundles (Also are the contents in "Bundles2" of the old implementation: "VisualGGPK2", which is not actually the real structure in ggpk).

To extract things in left one you need to use VisualGGPK3 or write your own program which reference LibGGPK3

**Comment by Azperin** [comment]
Which exe I can use to parse .dat64 files ? Really miss some readme =)

**Comment by aianlinb** [comment]
@Azperin Use `VisualGGPK2` please.
This repository is for developers only and is still under development.
