### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by hu2jin2yu2** [aianlinb/LibGGPK3#13]
如题 我在mac上无法点开显示编码utf-8不适用

**Comment by aianlinb** [comment]
點開什麼?

**Comment by hu2jin2yu2** [comment]
![Uploading 截屏2023-11-10 21.10.35.png…]()

**Comment by aianlinb** [comment]
@hu2jin2yu2 你圖片沒有上傳成功

先猜你是類似的問題:
https://github.com/aianlinb/LibGGPK3/pull/10/commits/c434ddb6d3f2aae8de1dcc4603edade0e78f52c8

還有問題建議去編年史Discord的中文漢化頻道，釘選訊息有教學
