### ISSUE TITLE
mac版本应该运行哪个文件呀？

### ISSUE THREAD

**Issue by haihaipipiChen** [aianlinb/LibGGPK3#14]
如题，请教一下，点开VPatchGGPK3.app;VisualGGPK3.app均提示无法打开

**Comment by aianlinb** [comment]
@haihaipipiChen
M1和M2等系列晶片的mac下載osx-arm64
其餘下載osx-x64 (Intel處理器)

使用前均需安裝 [.Net Runtime 6.0.*](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) (非SDK)

打不開請嘗試:
1. 至 系統設定 -> 隱私權與安全性，檢查是否被系統阻擋
2. 在終端機中cd至osx-xxx資料夾，輸入 `chmod -R +x .` 和 `xattr -c -r .`

以上步驟都只有第一次執行時需要

arm64版本因未簽名的問題目前只能使用 [Pre-Release v1.1.0](https://github.com/aianlinb/LibGGPK3/releases/tag/Pre-v1.1.0) 版
除非你知道如何使用codesign手動為應用簽名

該程式庫目前尚未開發完全，開發完成後會盡力將以上繁瑣事項預先解決
目前仍不建議非Windows平台使用，可能有潛在的Bug
以上仍無法解決者請靜待未來更新

**Comment by haihaipipiChen** [comment]
感谢！
