### ISSUE TITLE
尝试开发一个替换字体的程序，成功读取了uisetting的内容，但是无法写入

### ISSUE THREAD

**Issue by sage9731** [aianlinb/LibGGPK3#15]
以下是代码，通过```_index.TryGetFile("metadata/ui/uisettings.tencent.xml", out var fileRecord)```读出了uisettings.tencent.xml的内容，修改后，重新通过FileRecord _tencentUiSetting对象写入，第一次能够写入成功，但通过VisualGGPK可以看到usettings.tencent.xml的内容没有发生改变，第二次写入报错 `A file/directory with the same is already exist: /Bundles/LibGGPK3/0.bundle.bin`。

通过调试看出FileRecord.cs:84 using var bundle = BundleRecord.Index.GetBundleToWrite(out var size);的方法中，程序是创建了一个CustomBundles进行写入，但我无法理解为什么代码是这样运作的，为什么没有直接写入usettings.tencent.xml所在的bundle?

```c#
           // _tencentUiSetting is FileRecord object
            var byteMemory = _tencentUiSetting.Read();
            var settingContent = System.Text.Encoding.Unicode.GetString(byteMemory.ToArray());

           // edit setting content...
            
            _tencentUiSetting.Write(new ReadOnlySpan<byte>(Encoding.UTF32.GetBytes(settingContent)));
````

**Comment by aianlinb** [comment]
寫入資料不需要和原本檔案在同個bundle，此為內部實現細節，使用者不須理會

**Comment by sage9731** [comment]
已上传了完整的代码，[仓库地址](https://github.com/sage9731/FontGGPK)，项目是在Example/FontGGPK

**Comment by aianlinb** [comment]
@sage9731 原封不動直接建置執行，成功替換沒有任何問題
![image](https://github.com/aianlinb/LibGGPK3/assets/29705994/aa3b5acd-375b-494a-bd04-97b91e161dfb)

**Comment by aianlinb** [comment]
@sage9731 你真的有試過刪除ggpk重新下載嗎?
有些損壞的ggpk是連PackCheck都無法修復的

**Comment by sage9731** [comment]
最初有备份ggpk再进行开发，看来一开始的备份就有问题

**Comment by sage9731** [comment]
感谢您的解答
