### ISSUE TITLE
Bundle内创建新的文件夹

### ISSUE THREAD

**Issue by mylylyl** [aianlinb/LibGGPK3#17]
作者你好，

请问bundle内可以创建新的文件夹吗？或者修改现有文件夹的名字？
看了代码没有看懂oodle的结构。。。

**Comment by aianlinb** [comment]
沒有辦法
更改目錄結構必須修改_.index.bin末端的路徑編碼塊
目前沒有打算實作此功能

**Comment by mylylyl** [comment]
谢谢！
不好意思再reopen一下，请问oodle结构有相关的资讯吗，还是只能自己reverse？

**Comment by aianlinb** [comment]
@mylylyl
與oodle無關
_.index.bin的格式可以在這裡參考
https://github.com/poe-tool-dev/ggpk.discussion/wiki/Bundle-scheme#bundle-file-format
