### ISSUE TITLE
2.6.3 can not translate ggpk file

### ISSUE THREAD

**Issue by machenme** [aianlinb/LibGGPK3#18]
2.6.3 can not translate ggpk file, back to 2.6.2 is ok
![d7e334e25660ff11debcba93a8ff7658](https://github.com/user-attachments/assets/7432fc0b-4a69-4a3e-a788-60aef6e8591d)

**Comment by aianlinb** [comment]
![image](https://github.com/user-attachments/assets/c2562fc8-e971-4baf-be46-1bdb399af923)
我無法重現你的問題，請重試或嘗試重新下載遊戲

**Comment by machenme** [comment]
我发现问题所在了,在运行PackCheck.exe结束之后,还需要运行一次poe的文件,他会自动更新17M左右的东西然后就能正常工作了.
