### ISSUE TITLE
Not working under CrossOver

### ISSUE THREAD

**Issue by lazywhite** [aianlinb/LibGGPK3#19]
I'm using Macbook M3, I run POE with CrossOver(24.0.5), I can't use this tool to do patch, here is GUI

<img width="649" alt="image" src="https://github.com/user-attachments/assets/2e2e622c-8f0e-4ef1-86ba-f1ab2e28666b">

it seems like .NET application can't run well under CrossOver.
It will be good if users can do patch all by CMD command with parameters

**Comment by lazywhite** [comment]
PoeChinese3_win-x64.exe is the CLI tool to do it.

**Comment by aianlinb** [comment]
Don't use LibGGPK3 in CrossOver. It has macOS versions.
