### ISSUE TITLE
Published LibGGPK3 has no comments

### ISSUE THREAD

**Issue by Urantij** [aianlinb/LibGGPK3#2]
If you install LibGGPK3 from nuget, you wont have any comments.
You can add
`<GenerateDocumentationFile>true</GenerateDocumentationFile>`
line within PropertyGroup element in .csproj file to include comments. You can also add
`<NoWarn>1591</NoWarn>`
To disable warning about not having comments on public props.

This will improve the usability of the library.

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>Library for Content.ggpk of game PathOfExile (Rewrite of LibGGPK2)</Description>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>1591</NoWarn>
	</PropertyGroup>
</Project>
```

**Comment by aianlinb** [comment]
Thanks, I'll add this in next version.
