### ISSUE TITLE
mac系统汉化流程如下

### ISSUE THREAD

**Issue by idler8** [aianlinb/LibGGPK3#22]
下载Linux版汉化软件PoeChinese：https://github.com/aianlinb/LibGGPK3/releases 
找个繁体字体，重命名为Font.ttf
将PoeChinese和Font.ttf放在Content.ggpk同目录下
安装运行Docker：https://www.docker.com
打开终端执行：docker run --rm -it -v (Content.ggpk目录绝对地址,不要括号):/POE ubuntu:22.04 bash
再输入命令完成汉化：/POE/PoeChinese3_linux-arm64 /POE/Content.ggpk
每次游戏更新，只需要执行后两句就可以了

@aianlinb macos版太难用了，弃了吧

旧的mac版汉化操作视频：https://www.bilibili.com/video/BV1ZX8ee8Er6

**Comment by aianlinb** [comment]
你不會用不代表它難用，明明都是同樣的步驟，硬要多裝一個docker執行其他系統的版本用意何在？
