### ISSUE TITLE
PoeChinese3 在Macos下运行

### ISSUE THREAD

**Issue by Sewens** [aianlinb/LibGGPK3#24]
设备：Mac mini4 m4。

尝试用命令行运行PoeChinese3，但是提示没有找到该命令：

![image](https://github.com/user-attachments/assets/9a923757-a592-4a08-8e50-be4adc2b4486)

**Comment by aianlinb** [comment]
不用sudo，另外記得要先chmod +x PoeChinese3_osx-x64

**Comment by Sewens** [comment]
了解了，感谢您！
