### ISSUE TITLE
VPatchGGPK3 execution results in an error.

### ISSUE THREAD

**Issue by EeroLai** [aianlinb/LibGGPK3#3]
Hi,
I'm interested in the tool you created, so I downloaded it and tried to run it. However, I unexpectedly found an error occurring at line 141 in MainWindow.cs when running Examples/VPatchGGPK3, specifically when calling the new GGPK(ggpkPath.Text) method. Could you please let me know how to fix this issue, or provide information on how it's supposed to run so that I can try to fix it myself?

![image](https://user-images.githubusercontent.com/84887419/235070920-80e5049b-d5f2-4a42-b403-165d2ab16833.png)

Thanks!

**Comment by aianlinb** [comment]
What error?

**Comment by EeroLai** [comment]
After cloning the repository and running the program, I clicked on the '套用中文化' button and encountered the following errors.

![image](https://user-images.githubusercontent.com/84887419/235073456-2580c560-a2f3-4940-9203-2d9ffd2a4d4d.png)
![image](https://user-images.githubusercontent.com/84887419/235073509-30cc9ae1-b636-4356-bc7f-bba2c19f9d35.png)

**Comment by aianlinb** [comment]
Will be fixed in next version.

If you want it to work immediately, just add a line at the beginning of the method:
```cs
var path = ggpkPath.text;
```
and replace all `ggpkPath.text` below with `path`
