### ISSUE TITLE
missing oo2core dll?

### ISSUE THREAD

**Issue by luisestrada115** [aianlinb/LibGGPK3#4]
Tried to run VisualGGPK3

When opening the Content.ggpk i am getting a missing oo2core dll error

System.DllNotFoundException: 'Unable to load DLL 'oo2core' or one of its dependencies: The specified module could not be found. (0x8007007E)'

>	LibBundle3.dll!LibBundle3.Bundle.ReadChunks(int start, int count) Line 134	C#
 	LibBundle3.dll!LibBundle3.Bundle.ReadData() Line 65	C#
 	LibBundle3.dll!LibBundle3.Index.Index(System.IO.Stream stream, bool leaveOpen, bool parsePaths) Line 116	C#
 	LibBundledGGPK3.dll!LibBundledGGPK.BundledGGPK.BundledGGPK(string filePath, bool parsePathsInIndex) Line 12	C#
 	VisualGGPK3.dll!VisualGGPK3.MainWindow..ctor.AnonymousMethod__6() Line 132	C#

**Comment by aianlinb** [comment]
@luisestrada115
https://github.com/aianlinb/LibGGPK3/releases/tag/v1.2.0
