### ISSUE TITLE
File not found: Data/Language.dat

### ISSUE THREAD

**Issue by chasingkirkjufell** [aianlinb/LibGGPK3#5]
After dragging dropping index.bin to PoeChinese3_win.exe and successfully exit the routine. Starting POE on steam throws this error.

![image](https://github.com/aianlinb/LibGGPK3/assets/38635377/f4858617-a393-4a82-bfe9-d0085c8c769a)

**Comment by aianlinb** [comment]
@chasingkirkjufell Fixed, recovery your ggpk by VisualGGPK2 or PackCheck, and use the latest version of PoeChinese3 (v1.4.0) try again.
