### ISSUE TITLE
解壓縮目錄會變成 dir;name

### ISSUE THREAD

**Issue by Chuanhsing** [aianlinb/LibGGPK3#7]
解壓縮目錄選定 Desktop，目錄名稱設定 audio，可是他總是輸出成 Desktop;audio

**Comment by aianlinb** [comment]
Fixed: v2.0.0-preview.1 https://github.com/aianlinb/LibGGPK3/commit/d284f41a9e2c2283f3d2d234fa5c653e4af9de22
