### ISSUE TITLE
请问下,关于下载包里没有LibBundle3或者LibBundledGGPK3的exe程序?

### ISSUE THREAD

**Issue by ouyangxxx** [aianlinb/LibGGPK3#8]
下载的包里没有LibBundle3或者LibBundledGGPK3的exe程序?现在的版本不提供这个功能了吗?
以前的LibBundle项目功能,只给2个文件,一个_.index.bin,另一个xxxx.bundle.bin,提取里边的所有文件
现在还有办法使用这个功能吗?
试过直接用VisualGGPK3.exe加载完整客户端的_.index.bin,里边太多了,没法只单独提取 xxxx.bundle.bin的文件.....

谢谢

**Comment by aianlinb** [comment]
不提供此功能，因為沒有必要
你必須自己寫一個程式引用LibBundle3並調用其函數
提醒你，如果你是要提取中文化的檔案，建議你先取得原作者的同意
